on: issues
name: Flits Uptime
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: Blockbook Down!!
        SLACK_USERNAME: CrapBot
        SLACK_ICON_EMOJI: 💩
        SLACK_MESSAGE: ${{ github.event.label.name }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
